name: Docker build geocontrib image

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/docker-build-geocontrib.yml'
      - 'geocontrib/**'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./geocontrib
          file: ./geocontrib/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/camptocamp/georchestra-docker-images/geocontrib:5.4.7
